// Generated by CoffeeScript 1.9.2
module.exports = function(lng, lat, zoom) {
  var n;
  n = Math.pow(2, zoom);
  return [Math.floor(n * ((lng + 180) / 360)), Math.floor(n * (1 - (Math.log(Math.tan(lat) + 1 / Math.cos(lat)) / Math.PI)) / 2), zoom];
};
