// Generated by CoffeeScript 1.9.2
var lnglattotilefloat;

lnglattotilefloat = require('lnglattotilefloat');

module.exports = function(lng, lat, zoom) {
  var result;
  result = lnglattotilefloat(lng, lat, zoom);
  result[0] = Math.floor(result[0]);
  result[1] = Math.floor(result[1]);
  return result;
};
